In [12]:
import requests

In [15]:
import requests

url = "https://wrds-api.wharton.upenn.edu/data-full/pitchsmp.wrds_company/?allowed-fields=activeinvestors%2Calternateofficecount%2Cbusinessstatus%2Ccompanyalsoknownas%2Ccompanyfinancingstatus%2Ccompanyformername%2Ccompanyid%2Ccompanylegalname%2Ccompanyname%2Cdescription%2Cemployees%2Cexchange%2Cfacebookprofileurl%2Cfinancingstatusnote%2Cfirstfinancingdate%2Cfirstfinancingdealclass%2Cfirstfinancingdealtype%2Cfirstfinancingdealtype2%2Cfirstfinancingdealtype3%2Cfirstfinancingsize%2Cfirstfinancingsizestatus%2Cfirstfinancingstatus%2Cformerinvestors%2Cgrowthrate%2Cgrowthratechange%2Cgrowthratepercentchange%2Cgrowthratepercentile%2Chqaddressline1%2Chqaddressline2%2Chqcity%2Chqcountry%2Chqemail%2Chqfax%2Chqglobalregion%2Chqglobalsubregion%2Chqlocation%2Chqphone%2Chqpostcode%2Chqstate_province%2Ckeywords%2Clastfinancingdate%2Clastfinancingdealclass%2Clastfinancingdealtype%2Clastfinancingdealtype2%2Clastfinancingdealtype3%2Clastfinancingsize%2Clastfinancingsizestatus%2Clastfinancingstatus%2Clastupdated%2Clinkedinprofileurl%2Cownershipstatus%2Cparentcompany%2Cpitchbookprofilelink%2Cprimaryindustrycode%2Cprimaryindustrygroup%2Cprimaryindustrysector%2Csizemultiple%2Csizemultiplechange%2Csizemultiplepercentchange%2Csizemultiplepercentile%2Csocialgrowthrate%2Csocialgrowthratepercentile%2Csocialsizemultiple%2Csocialsizemultiplepercentile%2Cticker%2Ctotalraised%2Ctwitterfollowers%2Ctwitterfollowerschange%2Ctwitterfollowerspercentchange%2Ctwittergrowthrate%2Ctwittergrowthratepercentile%2Ctwitterprofileurl%2Ctwittersizemultiple%2Ctwittersizemultiplepercentile%2Cuniverse%2Cwebgrowthrate%2Cwebgrowthratepercentile%2Cwebsite%2Cwebsizemultiple%2Cwebsizemultiplepercentile%2Cwrds_src%2Cyearfounded&drf_token=a9da6251ba096897b8e7e832e4b97d5a28ea528e&format=json&limit=1000&offset=0"
response = requests.get(url)
data = response.json()  # Assuming the response is in JSON format

In [19]:
results = data['results']

In [21]:
#df = pd.DataFrame(data["results"])
df = pd.DataFrame(results)
df

,activeinvestors,alternateofficecount,businessstatus,companyalsoknownas,companyfinancingstatus,companyformername,companyid,companylegalname,companyname,description,...,twittersizemultiple,twittersizemultiplepercentile,universe,webgrowthrate,webgrowthratepercentile,website,websizemultiple,websizemultiplepercentile,wrds_src,yearfounded
0,NaN,NaN,Generating Revenue,None,Corporate Backed or Acquired,None,100000-00,None,Reed Exhibitions (Food Services Events Operati...,Organizer of food services events. The company...,...,NaN,NaN,M&A,NaN,NaN,reedexhibitions.co.uk,NaN,NaN,ot_row,1960.0
1,NaN,NaN,Generating Revenue,None,Corporate Backed or Acquired,None,100000-09,Andriscos SAS,Andriscos,Provider of real estate services. The company ...,...,NaN,NaN,M&A,NaN,NaN,None,NaN,NaN,ot_row,2007.0
2,NaN,1.0,Profitable,Green Smoke,Corporate Backed or Acquired,None,100000-27,SIS Resources Ltd.,SIS Resources,Manufacturer of electronic cigarettes. The com...,...,NaN,NaN,M&A,-0.31,8.0,www.greensmoke.com,34.27,97.0,ot_row,2008.0
3,1.0,NaN,Profitable,None,Corporate Backed or Acquired,None,100000-54,Jade Dynasty Holdings Ltd.,Jade Dynasty Holdings,Provider of a publishing company. The company ...,...,NaN,NaN,M&A,NaN,NaN,None,NaN,NaN,ot_row,NaN
4,NaN,NaN,Profitable,None,Corporate Backed or Acquired,Hagby Bruk,100000-63,Sandvik Nora AB,Sandvik Nora,Manufacturer and seller of diamond tools and m...,...,NaN,NaN,M&A,NaN,NaN,www.hagby.se,NaN,NaN,ot_row,1960.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,4.0,NaN,Generating Revenue,None,Private Equity-Backed,None,97417-99,Silicon Ranch Corp.,Silicon Ranch,Developer and operator of solar energy plants ...,...,2.05,64.0,"Debt Financed, Private Equity, Venture Capital",NaN,NaN,www.siliconranch.com,NaN,NaN,pe_na,2011.0
463,NaN,1.0,Generating Revenue,None,Private Equity-Backed,None,98752-15,"Tissue Analytics, Inc.",Tissue Analytics,Developer of a tissue analytics platform desig...,...,1.29,55.0,"Private Equity, Venture Capital",0.29,93.0,www.tissue-analytics.com,5.62,85.0,pe_na,2014.0
464,NaN,1.0,Generating Revenue,None,Private Equity-Backed,None,98752-15,"Tissue Analytics, Inc.",Tissue Analytics,Developer of a tissue analytics platform desig...,...,1.29,55.0,"Private Equity, Venture Capital",0.29,93.0,www.tissue-analytics.com,5.62,85.0,vc_na,2014.0
465,1.0,NaN,Profitable,None,Private Equity-Backed,"DAVID SPEAKMAN TRAVEL LIMITED, INCENTIVE, MEDI...",98817-67,Travel Counsellors Ltd.,Travel Counsellors,Operator of a travel agency. The company's tra...,...,29.31,94.0,Private Equity,0.26,93.0,www.travelcounsellors.co.uk/gb/leisure,77.87,99.0,pe_row,1994.0
466,11.0,3.0,Generating Revenue,None,Venture Capital-Backed,BLOCKpeek,99122-50,Ava Information Systems GmbH,AVA,Developer of a data management platform design...,...,0.25,28.0,Venture Capital,NaN,NaN,www.ava.info,NaN,NaN,vc_row,2014.0

# Cleaning

1565